#!/usr/bin/env python3
"""Create and verify the source-rootfs identity embedded in candidate images."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import subprocess
import tarfile
import tempfile
from pathlib import Path
from typing import NoReturn


SCHEMA = "antigravity-ha-source-rootfs/v1"
MANIFEST_RELATIVE_PATH = Path(
    "usr/local/share/antigravity-ha/source-rootfs-manifest.json"
)
DIGEST_PATTERN = re.compile(r"^sha256:[0-9a-f]{64}$")
DOCKERIGNORE_HEADER = (
    "# Generated by .github/scripts/source-rootfs-manifest.py; do not edit.",
    "# Parent directories are traversal-only and resealed; every input file is explicit.",
)
DOCKER_CONTEXT_FILES = (
    Path("Dockerfile"),
    Path("playwright/package.json"),
    Path("playwright/package-lock.json"),
)
DOCKERIGNORE_UNSAFE_PATH = re.compile(r"[\s*?\[\]\\]")


class ManifestError(ValueError):
    """Raised when source-rootfs identity is incomplete or inconsistent."""


def fail(message: str) -> NoReturn:
    raise ManifestError(message)


def file_digest(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return f"sha256:{digest.hexdigest()}"


def source_files(root: Path) -> list[dict[str, object]]:
    root = root.resolve(strict=True)
    if not root.is_dir():
        fail("rootfs source is not a directory")
    try:
        for candidate in root.rglob("*"):
            metadata = candidate.lstat()
            if stat.S_ISDIR(metadata.st_mode) or stat.S_ISREG(metadata.st_mode):
                continue
            fail(
                "source-rootfs contains a non-regular path: "
                f"{candidate.relative_to(root).as_posix()}"
            )
    except OSError as error:
        fail(f"source-rootfs cannot be scanned safely: {error}")
    try:
        repository = Path(
            subprocess.check_output(
                ["git", "-C", str(root), "rev-parse", "--show-toplevel"],
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
        ).resolve(strict=True)
        root_relative = root.relative_to(repository)
        pathspec = "." if root_relative == Path(".") else f":(literal){root_relative.as_posix()}/"
        listed = subprocess.check_output(
            [
                "git",
                "-C",
                str(repository),
                "ls-files",
                "--cached",
                "--others",
                "--exclude-standard",
                "-z",
                "--",
                pathspec,
            ],
            stderr=subprocess.DEVNULL,
        )
        repository_paths = sorted(
            item.decode("utf-8") for item in listed.split(b"\0") if item
        )
    except (OSError, subprocess.CalledProcessError, UnicodeError, ValueError) as error:
        fail(f"rootfs must be inside a readable Git worktree: {error}")

    result: list[dict[str, object]] = []
    for repository_path in repository_paths:
        path = repository / repository_path
        try:
            relative = path.relative_to(root)
        except ValueError:
            fail("Git returned a path outside the requested rootfs")
        if relative == MANIFEST_RELATIVE_PATH:
            continue
        if not path.exists() and not path.is_symlink():
            continue
        metadata = path.lstat()
        if not stat.S_ISREG(metadata.st_mode):
            fail(f"source-rootfs contains a non-regular path: {relative.as_posix()}")
        result.append(
            {
                "path": f"/{relative.as_posix()}",
                "mode": "0755" if metadata.st_mode & 0o111 else "0644",
                "size": metadata.st_size,
                "sha256": file_digest(path),
            }
        )
    if not result:
        fail("source-rootfs manifest cannot be empty")
    return result


def rootfs_digest(files: list[dict[str, object]]) -> str:
    encoded = json.dumps(
        files,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return f"sha256:{hashlib.sha256(encoded).hexdigest()}"


def build_manifest(root: Path) -> dict[str, object]:
    files = source_files(root)
    return {
        "schema": SCHEMA,
        "source_rootfs_sha256": rootfs_digest(files),
        "files": files,
    }


def validate_manifest(document: object) -> dict[str, object]:
    if not isinstance(document, dict) or set(document) != {
        "schema",
        "source_rootfs_sha256",
        "files",
    }:
        fail("source-rootfs manifest keys are not exact")
    if document["schema"] != SCHEMA:
        fail("source-rootfs manifest schema is unsupported")
    if not isinstance(document["source_rootfs_sha256"], str) or not DIGEST_PATTERN.fullmatch(
        document["source_rootfs_sha256"]
    ):
        fail("source-rootfs manifest digest is invalid")
    files = document["files"]
    if not isinstance(files, list) or not files:
        fail("source-rootfs manifest files are empty")
    previous = ""
    for item in files:
        if not isinstance(item, dict) or set(item) != {
            "path",
            "mode",
            "size",
            "sha256",
        }:
            fail("source-rootfs file entry keys are not exact")
        path = item["path"]
        if (
            not isinstance(path, str)
            or not path.startswith("/")
            or any(ord(character) < 32 or ord(character) == 127 for character in path)
            or "//" in path
            or "/../" in f"{path}/"
            or path <= previous
        ):
            fail("source-rootfs file path is unsafe or unsorted")
        previous = path
        if not isinstance(item["mode"], str) or not re.fullmatch(
            r"0[0-7]{3}", item["mode"]
        ):
            fail("source-rootfs file mode is invalid")
        if not isinstance(item["size"], int) or item["size"] < 0:
            fail("source-rootfs file size is invalid")
        if not isinstance(item["sha256"], str) or not DIGEST_PATTERN.fullmatch(
            item["sha256"]
        ):
            fail("source-rootfs file digest is invalid")
    if document["source_rootfs_sha256"] != rootfs_digest(files):
        fail("source-rootfs aggregate digest does not match its file entries")
    return document


def load_manifest(path: Path) -> dict[str, object]:
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        fail(f"source-rootfs manifest is unreadable: {error}")
    return validate_manifest(document)


def write_manifest(path: Path, document: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            json.dump(document, stream, ensure_ascii=True, indent=2, sort_keys=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(0o644)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def dockerignore_path_for(root: Path, configured: Path | None = None) -> Path:
    if configured is not None:
        return configured
    try:
        return root.resolve(strict=True).parent / ".dockerignore"
    except OSError as error:
        fail(f"Docker context root cannot be resolved: {error}")


def verify_docker_context_sources(root: Path, dockerignore_path: Path) -> None:
    try:
        resolved_root = root.resolve(strict=True)
        context_root = dockerignore_path.parent.resolve(strict=True)
    except OSError as error:
        fail(f"Docker context source cannot be resolved: {error}")
    if resolved_root != context_root / "rootfs":
        fail("Docker context allowlist must be adjacent to its rootfs directory")
    for relative in DOCKER_CONTEXT_FILES:
        candidate = context_root / relative
        for parent in candidate.parents:
            if parent == context_root:
                break
            try:
                parent_metadata = parent.lstat()
            except OSError as error:
                fail(f"Docker context parent is missing: {parent}: {error}")
            if not stat.S_ISDIR(parent_metadata.st_mode) or parent.is_symlink():
                fail(f"Docker context parent is not a directory: {parent}")
        try:
            metadata = candidate.lstat()
        except OSError as error:
            fail(f"Docker context source is missing: {relative}: {error}")
        if not stat.S_ISREG(metadata.st_mode) or candidate.is_symlink():
            fail(f"Docker context source is not a regular file: {relative}")


def dockerignore_lines(document: object) -> list[str]:
    validated = validate_manifest(document)
    rootfs_files = {
        Path("rootfs") / str(item["path"]).lstrip("/")
        for item in validated["files"]
    }
    rootfs_files.add(Path("rootfs") / MANIFEST_RELATIVE_PATH)

    directories = {Path("playwright"), Path("rootfs")}
    for path in rootfs_files:
        for parent in path.parents:
            if parent == Path("."):
                break
            directories.add(parent)

    for path in (*DOCKER_CONTEXT_FILES, *directories, *rootfs_files):
        value = path.as_posix()
        if (
            not value
            or value.startswith("/")
            or value in {".", ".."}
            or "/../" in f"/{value}/"
            or "/./" in f"/{value}/"
            or DOCKERIGNORE_UNSAFE_PATH.search(value)
        ):
            fail(f"Docker context path cannot be represented exactly: {value!r}")

    lines = [*DOCKERIGNORE_HEADER, "**", "!Dockerfile"]
    for path in sorted(directories, key=lambda item: (len(item.parts), item.as_posix())):
        lines.append(f"!{path.as_posix()}/")
        lines.append(f"{path.as_posix()}/*")
    lines.extend(
        f"!{path.as_posix()}"
        for path in sorted((*DOCKER_CONTEXT_FILES[1:], *rootfs_files))
    )
    return lines


def dockerignore_content(document: object) -> str:
    return "\n".join(dockerignore_lines(document)) + "\n"


def write_dockerignore(path: Path, document: object) -> None:
    content = dockerignore_content(document)
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(0o644)
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def verify_dockerignore(path: Path, document: object) -> None:
    expected = dockerignore_content(document)
    try:
        metadata = path.lstat()
        if not stat.S_ISREG(metadata.st_mode) or path.is_symlink():
            fail("Docker context allowlist is not a regular file")
        actual = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        fail(f"Docker context allowlist is unreadable: {error}")
    if actual != expected:
        fail("Docker context allowlist is stale or contains unmanifested patterns")


def verify_source(root: Path, manifest_path: Path) -> dict[str, object]:
    expected = load_manifest(manifest_path)
    actual = build_manifest(root)
    if expected != actual:
        fail("candidate source-rootfs manifest does not match the current source")
    return actual


def normalized_mode(mode: int) -> str:
    return "0755" if mode & 0o111 else "0644"


def verify_installed(
    root: Path,
    manifest_path: Path,
    *,
    exact: bool = False,
) -> dict[str, object]:
    root = root.resolve(strict=True)
    document = load_manifest(manifest_path)
    expected_paths: set[Path] = set()
    for item in document["files"]:
        relative = Path(str(item["path"]).lstrip("/"))
        expected_paths.add(relative)
        candidate = root / relative
        try:
            metadata = candidate.lstat()
        except OSError as error:
            fail(f"installed source-rootfs entry is missing: {relative}: {error}")
        if not stat.S_ISREG(metadata.st_mode) or candidate.is_symlink():
            fail(f"installed source-rootfs entry is not a regular file: {relative}")
        if normalized_mode(metadata.st_mode) != item["mode"]:
            fail(f"installed source-rootfs mode differs: {relative}")
        if metadata.st_size != item["size"]:
            fail(f"installed source-rootfs size differs: {relative}")
        if file_digest(candidate) != item["sha256"]:
            fail(f"installed source-rootfs digest differs: {relative}")

    if exact:
        try:
            manifest_relative = manifest_path.resolve(strict=True).relative_to(root)
        except (OSError, ValueError) as error:
            fail(f"exact installed verification requires a manifest below root: {error}")
        allowed = expected_paths | {manifest_relative}
        actual: set[Path] = set()
        for candidate in root.rglob("*"):
            metadata = candidate.lstat()
            if stat.S_ISDIR(metadata.st_mode):
                continue
            if not stat.S_ISREG(metadata.st_mode) or candidate.is_symlink():
                fail(f"installed source-rootfs contains a non-regular path: {candidate.relative_to(root)}")
            actual.add(candidate.relative_to(root))
        if actual != allowed:
            fail("installed source-rootfs contains missing or unmanifested files")
    return document


def canonical_tar_name(name: str) -> str:
    while name.startswith("./"):
        name = name[2:]
    if name.startswith("/") or "\x00" in name or "/../" in f"/{name}/":
        fail("image export contains an unsafe archive path")
    return name


def tar_member_digest(archive: tarfile.TarFile, member: tarfile.TarInfo) -> str:
    stream = archive.extractfile(member)
    if stream is None:
        fail("image export entry cannot be read")
    digest = hashlib.sha256()
    for chunk in iter(lambda: stream.read(1024 * 1024), b""):
        digest.update(chunk)
    return f"sha256:{digest.hexdigest()}"


def verify_image_archive(archive_path: Path) -> dict[str, object]:
    manifest_name = MANIFEST_RELATIVE_PATH.as_posix()
    try:
        with tarfile.open(archive_path, mode="r:*") as archive:
            members: dict[str, tarfile.TarInfo] = {}
            for member in archive.getmembers():
                name = canonical_tar_name(member.name)
                if name in members:
                    fail("image export contains a duplicate archive path")
                members[name] = member
            manifest_member = members.get(manifest_name)
            if manifest_member is None or not manifest_member.isfile():
                fail("image source-rootfs manifest is missing or not regular")
            manifest_stream = archive.extractfile(manifest_member)
            if manifest_stream is None or manifest_member.size > 4 * 1024 * 1024:
                fail("image source-rootfs manifest is unreadable or oversized")
            try:
                document = validate_manifest(json.loads(manifest_stream.read().decode("utf-8")))
            except (UnicodeError, json.JSONDecodeError) as error:
                fail(f"image source-rootfs manifest is invalid: {error}")
            for item in document["files"]:
                name = str(item["path"]).lstrip("/")
                member = members.get(name)
                if member is None or not member.isfile() or member.islnk() or member.issym():
                    fail(f"image source-rootfs entry is missing or not regular: {name}")
                if member.uid != 0 or member.gid != 0:
                    fail(f"image source-rootfs ownership differs: {name}")
                if normalized_mode(member.mode) != item["mode"]:
                    fail(f"image source-rootfs mode differs: {name}")
                if member.size != item["size"]:
                    fail(f"image source-rootfs size differs: {name}")
                if tar_member_digest(archive, member) != item["sha256"]:
                    fail(f"image source-rootfs digest differs: {name}")
            return document
    except (OSError, tarfile.TarError) as error:
        fail(f"image export is unreadable: {error}")


def verify_image(
    image: str,
    expected_revision: str,
    expected_source_rootfs_sha256: str,
) -> dict[str, object]:
    if not image or any(character in image for character in "\r\n\x00"):
        fail("image reference is invalid")
    if not re.fullmatch(r"[0-9a-f]{40}", expected_revision) or expected_revision == "0" * 40:
        fail("expected source revision is invalid")
    if not DIGEST_PATTERN.fullmatch(expected_source_rootfs_sha256):
        fail("expected source-rootfs digest is invalid")
    try:
        inspected = json.loads(subprocess.check_output(
            ["docker", "image", "inspect", image],
            stderr=subprocess.DEVNULL,
            text=True,
        ))
    except (OSError, subprocess.CalledProcessError, json.JSONDecodeError) as error:
        fail(f"candidate image cannot be inspected: {error}")
    if not isinstance(inspected, list) or len(inspected) != 1 or not isinstance(inspected[0], dict):
        fail("candidate image inspection is ambiguous")
    image_id = inspected[0].get("Id")
    config = inspected[0].get("Config")
    labels = config.get("Labels") if isinstance(config, dict) else None
    if not isinstance(image_id, str) or not DIGEST_PATTERN.fullmatch(image_id):
        fail("candidate image ID is not immutable")
    if not isinstance(labels, dict):
        fail("candidate image labels are missing")
    revision = labels.get("org.opencontainers.image.revision")
    source_rootfs = labels.get("io.antigravity-ha.source-rootfs-sha256")
    if revision != expected_revision:
        fail("candidate image revision label is stale")
    if source_rootfs != expected_source_rootfs_sha256:
        fail("candidate image source-rootfs label is stale")

    container_id: str | None = None
    with tempfile.TemporaryDirectory(prefix="antigravity-source-image-") as temporary:
        archive_path = Path(temporary) / "rootfs.tar"
        try:
            container_id = subprocess.check_output(
                [
                    "docker",
                    "create",
                    "--network",
                    "none",
                    "--entrypoint",
                    "/bin/true",
                    image_id,
                ],
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
            if not re.fullmatch(r"[0-9a-f]{64}", container_id):
                fail("candidate verification container ID is invalid")
            subprocess.run(
                ["docker", "export", "--output", str(archive_path), container_id],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            document = verify_image_archive(archive_path)
        except (OSError, subprocess.CalledProcessError) as error:
            fail(f"candidate image cannot be exported: {error}")
        finally:
            if container_id is not None:
                subprocess.run(
                    ["docker", "rm", "--force", container_id],
                    check=False,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
    if document["source_rootfs_sha256"] != expected_source_rootfs_sha256:
        fail("candidate manifest, label, and expected source-rootfs digest differ")
    return {
        "schema": "antigravity-ha-source-image-verification/v1",
        "image_id": image_id,
        "revision": revision,
        "source_rootfs_sha256": source_rootfs,
        "verified_files": len(document["files"]),
    }


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("create", "verify"):
        subparser = subparsers.add_parser(command)
        subparser.add_argument("--root", required=True, type=Path)
        subparser.add_argument("--manifest", required=True, type=Path)
        subparser.add_argument(
            "--dockerignore",
            type=Path,
            help="Docker context allowlist (default: ROOT/../.dockerignore)",
        )
    installed = subparsers.add_parser("verify-installed")
    installed.add_argument("--root", required=True, type=Path)
    installed.add_argument("--manifest", required=True, type=Path)
    installed.add_argument("--exact", action="store_true")
    image = subparsers.add_parser("verify-image")
    image.add_argument("--image", required=True)
    image.add_argument("--expected-revision", required=True)
    image.add_argument("--expected-source-rootfs-sha256", required=True)
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    try:
        if arguments.command == "create":
            document = build_manifest(arguments.root)
            dockerignore_path = dockerignore_path_for(
                arguments.root,
                arguments.dockerignore,
            )
            verify_docker_context_sources(arguments.root, dockerignore_path)
            # Render before either write so unsupported path syntax fails without
            # partially refreshing the source identity.
            dockerignore_content(document)
            write_manifest(arguments.manifest, document)
            write_dockerignore(dockerignore_path, document)
            verify_dockerignore(dockerignore_path, document)
        elif arguments.command == "verify":
            document = verify_source(
                arguments.root,
                arguments.manifest,
            )
            dockerignore_path = dockerignore_path_for(
                arguments.root,
                arguments.dockerignore,
            )
            verify_docker_context_sources(arguments.root, dockerignore_path)
            verify_dockerignore(
                dockerignore_path,
                document,
            )
        elif arguments.command == "verify-installed":
            document = verify_installed(
                arguments.root,
                arguments.manifest,
                exact=arguments.exact,
            )
        else:
            evidence = verify_image(
                arguments.image,
                arguments.expected_revision,
                arguments.expected_source_rootfs_sha256,
            )
            print(json.dumps(evidence, ensure_ascii=True, sort_keys=True))
            return 0
        print(document["source_rootfs_sha256"])
        return 0
    except ManifestError as error:
        print(f"source-rootfs manifest error: {error}", file=os.sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
