#!/bin/bash -p
set -Eeuo pipefail
unset BASH_ENV ENV NODE_OPTIONS NODE_PATH SUPERVISOR_TOKEN

exec /usr/bin/env -i \
  AGY_CLI_DISABLE_AUTO_UPDATE=true \
  HOME=/data/home \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8 \
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  TERM=xterm-256color \
  /usr/local/libexec/antigravity-real "$@"
