#!/bin/bash -p
set -Eeuo pipefail
unset BASH_ENV ENV NODE_OPTIONS NODE_PATH SUPERVISOR_TOKEN
unset GLIBC_TUNABLES LD_AUDIT LD_DEBUG LD_LIBRARY_PATH LD_PRELOAD
unset PYTHONHOME PYTHONINSPECT PYTHONPATH PYTHONSTARTUP
unset GCONV_PATH GETCONF_DIR HOSTALIASES LOCALDOMAIN LOCPATH MALLOC_TRACE
unset NLSPATH RES_OPTIONS TMPDIR TZDIR

exec /usr/bin/env --default-signal=INT --default-signal=QUIT -i \
  AGY_CLI_DISABLE_AUTO_UPDATE=true \
  HOME=/data/home \
  LANG=C.UTF-8 \
  LC_ALL=C.UTF-8 \
  PATH=/usr/local/libexec/antigravity-command-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  TERM="${TERM:-xterm-256color}" \
  /usr/bin/setpriv --pdeathsig KILL \
  /usr/local/libexec/antigravity-native-session-guard sensitive-read "$@"
